language: node_js

node_js:
  - node

before_script:
 - npm install -g codeclimate-test-reporter
addons:
  code_climate:
    repo_token: 9QbsWNLCMgin3h9jigr4

before_install:
  - export CHROME_BIN=google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install

script: npm test

after_success:
  - codeclimate-test-reporter < coverage/lcov.info