language: node_js

node_js:
  - node

services:
  - mongodb

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'

before_install:
  - export CHROME_BIN=google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: npm test